routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [
    'uses' => 'ProductController@getIndex',
    'as' => 'product.index'
]);
Route::get('/book/search', 'SearchController@search');

Route::get('/add-to-cart/{id}', [
    'uses' => 'ProductController@getAddToCart',
    'as' => 'product.addToCart'
]);

Route::get('/product/{slug}', [
   'uses' => 'ProductController@showProduct',
   'as' => 'product.show'
]);

Route::get('/reduce{id}', [
    'uses' => 'ProductController@getReduceByOne',
    'as' => 'product.reduceByOne'
]);

Route::get('remove/{id}', [
   'uses' => 'ProductController@getRemoveItem',
    'as' => 'product.remove'
]);

Route::get('/shopping-cart', [
    'uses' => 'ProductController@getCart',
    'as' => 'product.shopping-cart'
]);

Route::get('/checkout', [
    'uses' => 'ProductController@getCheckout',
    'as' => 'checkout',

]);

Route::post('/checkout', [
    'uses' => 'ProductController@postCheckout',
    'as' => 'checkout',

]);

Route::group(['prefix' => 'users'], function (){
    Route::group(['middleware' => 'guest'], function (){
        Route::get('/signup', [
            'uses' => 'UserController@getSignup',
            'as' => 'users.signup',
        ]);

        Route::post('/signup', [
            'uses' => 'UserController@postSignup',
            'as' => 'users.signup',
        ]);

        Route::get('/signin', [
            'uses' => 'UserController@getSignin',
            'as' => 'users.signin',
        ]);
        Route::post('/signin', [
            'uses' => 'UserController@postSignin',
            'as' => 'users.signin',
        ]);
    });

    Route::group(['middleware' => 'auth'], function (){
        Route::get('/profile', [
            'uses' => 'UserController@getProfile',
            'as' => 'users.profile',
        ]);

        Route::get('/logout', [
            'uses' => 'UserController@getLogout',
            'as' => 'users.logout',
        ]);

        Route::group(['middleware' => 'admin'], function () {
            Route::resource('admin', 'AdminController');
//            Route::get('/admin', [
//                'uses' => 'AdminController@index',
//                'as'   => 'admin.profile',
//            ]);
//            Route::get('/admin/create', [
//                'uses' => 'AdminController@create',
//                'as'   => 'admin.create',
//            ]);
//            Route::post('/admin/create', [
//                'uses' => 'AdminController@store',
//                'as'   => 'admin.store',
//            ]);
        });

    });
});

resources/views/shop/admin-product.blade.php
@extends('layouts.master')

@section('title')
    Laravel Shopping Cart
@endsection

@section('content')
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <div class="row">
        <form action="{{ route('admin.update', [$product->id]) }}" method="post" enctype="multipart/form-data">
            {{ csrf_field() }}
            <input type="hidden" name="_method" value="patch"/>
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <img src="{{ asset('/img/shopping_cart/pencil.png') }}" id="product_img_edit" alt=""
                         style="width: 24px; margin-right: 0;">
                    <img src="{{asset($product->imagePath)}}" id="product_img" alt="...">
                    <input type="file" name="image" id="img_input" style="display: none;" onchange="readURL(this);">
                </div>
            </div>
            <div class="col-sm-6 col-md-6">
                <div class="caption">
                    <h3>Title</h3>
                    <input type="text" name="title" class="form-control" value="{{$product->title}}">
                    <div class="clearfix">
                    </div>
                    <label for="author">Author</label>
                    <input type="text" class="form-control" name="author" value="{{$product->author}}">
                    <label for="pages">Pages</label>
                    <input type="text" class="form-control" name="pages" value="{{$product->pages}}">
                    <label for="availability">Availability</label>
                    <input type="text" class="form-control" name="availability" value="{{$product->availability}}">
                    <label for="price">Price</label>
                    <input type="text" class="form-control" name="price" value="{{$product->price}}">

                </div>
            </div>
            <hr>
            <br>
            {{--<div class="row">--}}
                <textarea name="description" class="form-control description" rows="8" style="resize: none;">{{$product->description}}</textarea>
                <br>
                <br>
                <button type="submit" class="btn btn-primary" role="button">Update changes</button>
                <hr>
            {{--</div>--}}
        </form>
    </div>


@endsection

resources/views/shop/checkout.blade.php
@extends('layouts.master')

@section('title')
    Laravel Shopping Cart
@endsection

@section('content')
    <div class="row">
        <div class="col-sm-6 col-md-4 col-md-offset-4 col-sm-offset-3">
            <h1>Checkout</h1>
            <h4>Your Total: ${{ $total }}</h4>
            <div id="charge-error" class="alert alert-danger {{ !Session::has('error') ? 'hidden' : '' }}">
                {{ Session::get('error') }}
            </div>
            <form action="{{ route('checkout') }}" method="post" id="checkout-form">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="form-group">
                            <label for="name">Name</label>
                            <input type="text" id="name" class="form-control" name="name" required>
                        </div>
                    </div>
                    <div class="col-xs-12">
                        <div class="form-group">
                            <label for="address">Address</label>
                            <input type="text" id="address" class="form-control" name="address" required>
                        </div>
                    </div>
                    <div class="col-xs-12">
                        <div class="form-group">
                            <label for="card-name">Card Holder Name</label>
                            <input type="text" id="card-name" class="form-control" required>
                        </div>
                    </div>
                    <div class="col-xs-12">
                        <div class="form-group">
                            <label for="card-number">Card Number</label>
                            <input type="text" id="card-number" class="form-control" required>
                        </div>
                    </div>
                    <div class="col-xs-12">
                        <div class="row">
                            <div class="col-xs-6">
                                <div class="form-group">
                                    <label for="card-expiry-month">Expiration Month</label>
                                    <input type="text" id="card-expiry-month" class="form-control" required>
                                </div>
                            </div>
                            <div class="col-xs-6">
                                <div class="form-group">
                                    <label for="card-expiry-year">Expiration Year</label>
                                    <input type="text" id="card-expiry-year" class="form-control" required>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12">
                        <div class="form-group">
                            <label for="card-cvc">CVC</label>
                            <input type="text" id="card-cvc" class="form-control" required>
                        </div>
                    </div>
                </div>
                {{csrf_field()}}
                <button type="submit" class="btn btn-success" id="button">Buy now</button>
            </form>
        </div>
    </div>
@endsection

@section('scripts')
<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
<script type="text/javascript" src="{{ URL::to('/js/checkout.js') }}"></script>
@endsection

resources/views/shop/index.blade.php
@extends('layouts.master')

@section('title')
    Laravel Shopping Cart
@endsection

@section('content')
    @if(Session::has('success'))
        <div class="row">
            <div class="col-sm-6 col-md-4 col-md-offset-4 col-sm-offset-3">
                <div id="charge-mesage" class="alert alert-success">
                    {{Session::get('success')}}
                </div>
            </div>
        </div>
    @endif
    <div class="row">
        <div class="col-sm-6 col-md-4">
            <div id="search">
                <search></search>
            </div>
        </div>
    </div>
    <br>
    @foreach($products->chunk(3) as $productChunk)
    <div class="row">
        @foreach($productChunk as $product)
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <a href="{{ route('product.show', ['slug' =>$product->slug]) }}"><img src="{{asset($product->imagePath)}}" alt="..."></a>
                <div class="caption">
                    <h3>{{$product->title}}</h3>
                    <p class="description">{{str_limit($product->shortDescription, 80)}}</p>
                    <div class="clearfix">
                        <div class="pull-left price">${{$product->price}}</div>
                        <a href="{{ route('product.addToCart', ['id' => $product->id])}}" class="btn btn-success pull-right" role="button">Add to Cart</a>
                    </div>
                </div>
            </div>
        </div>
        @endforeach
    </div>
    @endforeach
    <div class="text-center">{{$products->links()}}</div>
@endsection

resources/views/shop/product.blade.php
@extends('layouts.master')

@section('title')
    Laravel Shopping Cart
@endsection

@section('content')
    @foreach($product as $item)
        <div class="row">
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <img src="{{'/'.$item['imagePath']}}" alt="...">
                </div>
            </div>
            <div class="col-sm-6 col-md-6">
                <div class="caption">
                    <h3>{{$item['title']}}</h3>
                    <div class="clearfix">

                    </div>
                    <ul class="list-group">

                        <li class="list-group-item">Author: <span class="pull-right">{{$item['author']}}</span></li>
                        <li class="list-group-item">Number of pages:<span class="pull-right">{{$item['pages']}}</span>
                        </li>
                        <li class="list-group-item">Availability: <span
                                    class="pull-right">{{$item['availability']}}</span></li>
                        <li class="list-group-item">Price:<span class="pull-right price"> ${{$item['price']}}</span>
                        </li>
                    </ul>
                    <a href="{{ route('product.addToCart', ['id' => $item['id']])}}" class="btn btn-success"
                       role="button">Add to Cart</a>
                </div>
            </div>
        </div>
        <hr>
        <div class="row">
            <p class="description">{{$item['description']}}</p>
        </div>
    @endforeach
@endsection

resources/views/shop/shopping-cart.blade.php
@extends('layouts.master')

@section('title')
    Laravel Shopping Cart
@endsection
@section('content')
    @if(Session::has('cart'))
        <div class="row">
            <div class="col-sm-6 col-md-6 col-md-offset-3 col-sm-offset-3">
                <ul class="list-group">
                    @foreach($products as $product)
                        <li class="list-group-item">
                            <span class="badge">{{ $product['qty'] }}</span>
                            <strong>{{ $product['item']['title'] }}</strong>
                            <span class="label label-success">${{ $product['price'] }}</span>
                            <div class="btn-group">
                                <button class="btn btn-primary btn-xs dropdown-toogle" data-toggle="dropdown">Action
                                    <span class="caret"></span></button>
                                <ul class="dropdown-menu">
                                    <li><a href="{{ route('product.reduceByOne', ['id' => $product['item']['id']]) }}">Reduce by 1</a></li>
                                    <li><a href="{{ route('product.remove', ['id' => $product['item']['id']]) }}">Reduce All</a></li>
                                </ul>
                            </div>
                        </li>
                    @endforeach
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6 col-md-6 col-md-offset-3 col-sm-offset-3">
                <strong>
                    Total: ${{$totalPrice}}
                </strong>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6 col-md-6 col-md-offset-3 col-sm-offset-3">
                <a href="{{ route('checkout')}}" type="button" class="btn btn-success">Checkout</a>
            </div>
        </div>
    @else
        <div class="row">
            <div class="col-sm-6 col-md-6 col-md-offset-3 col-sm-offset-3">
                <h2>
                    No Items in Cart!!
                </h2>
            </div>
        </div>
    @endif
@endsection